API_BASE_URL=http://172.16.29.76:8080
REGISTER=/register
REFREST_TOKEN=/refresh-token

USERS=/users
SAVE_MESSAGES=/messages
CONVERSATIONS=/conversations
MESSAGES=/messages/{userId}

GROUPS=/groups
GROUPS_MESSAGE=/groups/{groupId}/messages
