set(APP_NAME "ChatApp")

set(APP_VERSION_MAJOR 1)
set(APP_VERSION_MINOR 0)
set(APP_VERSION_PATCH 0)
set(APP_VERSION
    "${APP_VERSION_MAJOR}.${APP_VERSION_MINOR}.${APP_VERSION_PATCH}"
)

set(APP_BUILD_NUMBER 1)
set(APP_BUNDLE_IDENTIFIER "com.example.chatapp")
set(APP_ORGANIZATION_NAME "Your Company")
set(APP_ORGANIZATION_DOMAIN "example.com")
